version: '3'
services:
  trading:
    container_name: trading
    image: ghcr.io/the-microservice-dungeon/trading/tradingservice:latest
    env_file:
            - tradingService.env
            - ../services.env
    ports:
      - "8083:8080"
    expose:
      - "8080"
    networks:
      - tradingNet
      - mainNet

  mysqltrading:
    container_name: mysqltrading
    image: mysql:8
    restart: always
    env_file:
      - tradingDB.env
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - tradingNet
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: 


networks:
  tradingNet:
    external: true
  mainNet:
    external: true
