version: '3'
services:
  robot:
    container_name: robot
    image: ghcr.io/the-microservice-dungeon/robot/robotservice:latest
    env_file:
      - robotService.env
      - ../services.env
    ports:
      - "8082:8080"
    expose:
      - "8080"
    networks:
      - robotNet
      - mainNet
  mariadb-robot:
    container_name: mariadb-robot
    image: mariadb:10.6.5
    restart: always
    env_file:
      - robotDB.env
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - robotNet
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
networks:
  robotNet:
    external: true
  mainNet:
    external: true
