version: '3'
services:
  mariadb-robot:
    container_name: mariadb-robot
    image: mariadb:10.6.5
    restart: always
    env_file:
      - robotDB.env
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - robotNet
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:

networks:
  robotNet:
    external: true
