version: '3'
services:
  mysqlgamelog:
    container_name: mysqlgamelog
    platform: linux/x86_64
    image: mysql:8
    restart: always
    env_file:
      - gamelogDB.env
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - gamelogNet
    volumes:
      - dbdata:/var/lib/mysql

volumes:
    dbdata:

networks:
    gamelogNet:
        external: true
