version: '3'
services:
  mysqlgame:
    container_name: mysqlgame
    image: mysql:8
    restart: always
    env_file:
      - gameDB.env
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - gameNet
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:

networks:
  gameNet:
    external: true
